name: Publish to PyPI

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      # Step 3: Install dependencies
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          
      # Step 4: Install dependencies using Poetry
      - name: Install dependencies
        run: |
          poetry install

      # Step 5: Build the package
      - name: Build package
        run: |
          poetry build

      # Step 6: Upload the package to PyPI using Twine
      - name: Upload to PyPI
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          pip install twine
          twine upload dist/*

